# -*- coding: utf-8 -*-
"""Projet_train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iaXttPnKjna1fCQShXXnp486-TwYA6EX
"""

!pip install roboflow ultralytics -q

from roboflow import Roboflow

rf = Roboflow(api_key="t4eAh6uor6xxr0HE1RtG")
project = rf.workspace("matteos-workspace-f2qmj").project("landing_pad-nm9u3")
version = project.version(2)
dataset = version.download("yolov11")

import os

dataset_path = dataset.location
print("Chemin du dataset :", dataset_path)
print("\nContenu :")
for root, dirs, files in os.walk(dataset_path):
    level = root.replace(dataset_path, '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent}{os.path.basename(root)}/')
    if level < 2:
        subindent = ' ' * 2 * (level + 1)
        for f in files[:3]:
            print(f'{subindent}{f}')

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data=f"{dataset.location}/data.yaml",
    imgsz=640,
    epochs=50,
    batch=16,
    patience=20,
    save=True,
    plots=True,
    project="landing_pad",
    name="run1"
)

metrics = model.val(
    split="test",
    conf=0.25,
    iou=0.6
)

print(f"Précision   : {metrics.box.p.mean():.3f}")
print(f"Rappel      : {metrics.box.r.mean():.3f}")
print(f"mAP@0.5     : {metrics.box.map50:.3f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.3f}")

import numpy as np
from ultralytics import YOLO

model = YOLO("/content/runs/detect/landing_pad/run12/weights/best.pt")

val_results = model.predict(
    source=f"{dataset.location}/valid/images",
    conf=0.01,
    iou=0.6,
    save=False,
    verbose=False
)

records = []
for r in val_results:
    img_area = r.orig_shape[0] * r.orig_shape[1]
    img_name = r.path.split("/")[-1]

    if len(r.boxes) == 0:
        records.append({
            "image": img_name,
            "max_conf": 0.0,
            "area_ratio": 0.0,
            "has_gt": True
        })
    else:
        best_idx = r.boxes.conf.argmax()
        conf = float(r.boxes.conf[best_idx])
        box = r.boxes.xywh[best_idx]
        area_ratio = float((box[2] * box[3]) / img_area)

        records.append({
            "image": img_name,
            "max_conf": round(conf, 4),
            "area_ratio": round(area_ratio, 4),
            "has_gt": True
        })


print(f"{'Image':<30} {'Conf':>6} {'Area%':>7}")
print("-" * 46)
for rec in records:
    print(f"{rec['image']:<30} {rec['max_conf']:>6.3f} {rec['area_ratio']*100:>6.1f}%")

print("\n=== Exploration des seuils ===\n")
print(f"{'τ_conf':<8} {'τ_area':<8} {'Safe%':>6} {'Missed':>7}")
print("-" * 35)

for tau_conf in [0.3, 0.4, 0.5, 0.6, 0.7]:
    for tau_area in [0.01, 0.03, 0.05]:
        safe = sum(
            1 for r in records
            if r["max_conf"] >= tau_conf and r["area_ratio"] >= tau_area
        )
        missed = len(records) - safe
        print(f"{tau_conf:<8.1f} {tau_area:<8.2f} {safe:>5}/{len(records)} {missed:>6} missed")
    print()

TAU_CONF = 0.50
TAU_AREA = 0.01

print("=" * 40)
print(f"Seuils gelés : τ_conf={TAU_CONF} | τ_area={TAU_AREA}")
safe_val = sum(1 for r in records if r["max_conf"] >= TAU_CONF and r["area_ratio"] >= TAU_AREA)
print(f"Validation   : {safe_val}/36 SAFE | {36 - safe_val}/36 NOT SAFE (pad trop loin)")
print("=" * 40)
test_results = model.predict(
    source=f"{dataset.location}/test/images",
    conf=0.01,
    iou=0.6,
    save=False,
    verbose=False
)

print(f"\n{'Image':<45} {'Conf':>6} {'Area%':>7} {'Décision':>12}")
print("-" * 75)

safe_count = 0
for r in test_results:
    img_area = r.orig_shape[0] * r.orig_shape[1]
    img_name = r.path.split("/")[-1][:44]

    if len(r.boxes) == 0:
        conf, area = 0.0, 0.0
    else:
        best_idx = r.boxes.conf.argmax()
        conf = float(r.boxes.conf[best_idx])
        box = r.boxes.xywh[best_idx]
        area = float((box[2] * box[3]) / img_area)

    decision = "✅ SAFE" if (conf >= TAU_CONF and area >= TAU_AREA) else "❌ NOT SAFE"
    if decision == "✅ SAFE":
        safe_count += 1

    print(f"{img_name:<45} {conf:>6.3f} {area*100:>6.1f}% {decision:>12}")

print(f"\nRésultat final test : {safe_count}/{len(test_results)} SAFE | {len(test_results)-safe_count}/{len(test_results)} NOT SAFE")

from google.colab import files
files.download("/content/runs/detect/landing_pad/run12/weights/best.pt")